version: "3.9"
services:
  meili:
    build:
      context: .
      dockerfile: Dockerfile
  ports:
    - "7720:7700"
  volumes:
    - "/mybookone/docker/meili/data/data.ms":"/data.ms"
  environment:
    - MEILI_NO_ANALYTICS=true
    - MEILI_NO_SENTRY=true
    - MEILI_MASTER_KEY=test_api_key123123
